### PR TITLE
make it compile with glibc-2.26 with an explicit cast to bool

### PR DESCRIPTION
**Pull request by bulwahn**
With glibc-2.26, openslam_gmapping failed to compile with:
```
| [...]/gridfastslam/gfsreader.cpp: In member function 'virtual void GMapping::GFSReader::RawOdometryRecord::read(std::istream&)':
| [...]/gridfastslam/gfsreader.cpp:79:3: error: no match for 'operator==' (operand types are 'std::istream {aka std::basic_istream<char>}' and 'int')
|    assert(is);
|    ^
```

Hence, this commit explicitly casts to bool, so that the assert annotation compiles properly again. The issue was discovered during the maintenance of meta-ros, the OpenEmbedded layer for ROS.

### CODE REVIEW

**Review by k-okada — CHANGES_REQUESTED** [review]
@bulwahn   could you create new PR against `melodic-devel` branch? we have switched from `master` to `melodic-branch` when we changed licence to BSD
